name: build
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/actionshq/devcontainer:v0.1.2
    steps:
    - uses: actions/checkout@v4
    - run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
    - run: ./scripts/init.sh
    - run: ./scripts/check.sh
    - run: ./scripts/build.sh
