name: release
on:
  release:
    types: [released]
jobs:
  release:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/actionshq/devcontainer:v0.1.0
    steps:
    - uses: actions/checkout@v3
    - run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
    - run: ./scripts/init.sh
    - run: ./scripts/build.sh
    - run: ./scripts/release.sh
