name: stage
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  packages: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/actionshq/devcontainer:v0.1.2
    environment:
      name: staging
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v3
    - run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
    - run: ./scripts/init.sh
    - run: ./scripts/check.sh
    - run: ./scripts/build.sh
    - uses: actions/configure-pages@v5
    - uses: actions/upload-pages-artifact@v1
      with:
        path: dist/client
    - id: deployment
      uses: actions/deploy-pages@v1
